import React from 'react';
import Figure from 'react-bootstrap/Figure';
import { Grid } from '@mui/material';
function Traits(){

    return(
        <section>
            <div  className='container traitContainer'>
                <Grid container spacing = {2}>
                    <Grid item xs={6}>
                        <div className='descriptionTxt'>
                        <h3 className="display-8"> How are they created? </h3>
                        <p>
                            Each WEIRDO is algorithmically generated by combining 190+ traits in such a manner that no two Weirdoz are the same <br></br>
                            19 of them are fully designed by the 2 artists (sounds rare!)
                        </p>
                        <p className='lead'> Grab your unique NFT right now !</p>
                        </div>
                    </Grid>
                    <Grid item xs={6}>
                    <figure className="descriptionImg figure-img img-fluid ">
                        <Figure.Image
                            alt="2000.2000"
                            src="img/imgtraits.png"
                        />
                    </figure>
                    </Grid>
                </Grid>
            </div>
        </section>
    )

}

export default Traits;